package com.llama.basilisk.sample.model;

import com.llama.basilisk.Model;
import com.llama.basilisk.binding.Bindable;

/**
 * Created by Christian Ringshofer on 25.08.15.
 * the subscriber type could maybe be generated by the annotation processor
 */
@Model
public interface MyModel {

    Bindable<String> test();

}
