package com.llama.basilisk.sample.model;

import com.llama.basilisk.$$ModelBinder;
import com.llama.basilisk.BindGetter;
import com.llama.basilisk.BindSetter;
import com.llama.basilisk.Model;

/**
 * Created by Christian Ringshofer on 25.08.15.
 * the subscriber type could maybe be generated by the annotation processor
 */
@Model
public class TwoWayModel extends $$ModelBinder {

    private String test = "Basilisk";

    @BindGetter("test")
    public String getTest() {
        return this.test;
    }

    @BindSetter("test")
    public void setTest(final String test) {

        this.test = test;
        // should be auto generated
        super.bind(this.test);

    }

    @Override
    public void onCompleted() {

    }

    @Override
    public void onError(Throwable e) {

    }

    @Override
    public void onNext(Object s) {
        // should use generated / bound setter
        this.setTest(String.valueOf(s));
    }

}
