package com.llama.basilisk.sample.model;

import com.llama.basilisk.$$ModelBinder;
import com.llama.basilisk.Model;

/**
 * Created by Christian Ringshofer on 25.08.15.
 * the subscriber type could maybe be generated by the annotation processor
 */
@Model
public class TwoWayModel extends $$ModelBinder {

    private String test = "Basilisk";

    @Override
    public Object get(String key) {

        return this.test;

    }

    @Override
    public void set(String key, Object value) {

        this.test = (String) value;
        // should be auto generated
        super.bind();

    }

    @Override
    public void onCompleted() {

    }

    @Override
    public void onError(Throwable e) {

    }

    @Override
    public void onNext(Object s) {
        // should use generated / bound setter
        this.set("test", String.valueOf(s));
    }

}
